### ISSUE TITLE
Error when import template in angular2-meteor-base

### ISSUE THREAD

**Issue by juliocesar12** [Urigo/meteor-static-templates#12]
I was following these steps https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping, but when I launch the app of the demo, I get this in the browser:
/client/imports/app/app.component.html?hash=914ffc55559da1b3ec94ce03cc2c0ac8312632b7
I dont know if someone can help me please .
Thanks
![image](https://cloud.githubusercontent.com/assets/11258942/18796172/ae420180-818d-11e6-8b2c-6f0a6650ee74.png)

**Comment by kamilkisiela** [comment]
How do you use `app.component.html`?

Is it:

``` ts
import template from 'app.component.html';
// ...
@Component({
  template: template
})
// ... 
```

**Comment by Urigo** [comment]
this was updated and deployed. @juliocesar12 can you try again?
