### ISSUE TITLE
plugin-cache folder of this plugin exceeds 50GB after one day

### ISSUE THREAD

**Issue by SimonSimCity** [Urigo/meteor-static-templates#21]
@sebakerckhof I want you to please take a look at this.

One day I've updated to the version 1.1.1 which you published, the size of the folder `.meteor/local/plugin-cache/urigo_static-templates/1.1.1/` contains astonishing 62,400 items and is 65.91 GB in size. Do you have an idea what could've caused this? I'm now removing my `.meteor/local/` folder and thus clearing the meteor instance and reinstalling meteor itself to see if it helps, but otherwise, you have to tell me what and why you did the change here.

At first I was wondering what would drag down the build-time by almost 1sec, but now I see that it's this plugin ...

All this worked fine on v1.0.0_2 ...

**Comment by SimonSimCity** [comment]
Now started my project, where this folder already has 707 files. After changing a single file and thus causing meteor to rebuild the application, I already had 1179 files there, eating up 70MB. I'll try older versions of this plugin to see if they also suffer from this problem.

**Comment by SimonSimCity** [comment]
I saw that there was a version on atmosphere where the code is not published here. It's version is named `1.1.4`, but this and the version published before (`1.1.2`) should have their code in this repository.

Switching to `1.1.4` solved this problem. But I would like the code to be available in this repository.

**Comment by sebakerckhof** [comment]
yeah, I'm working on it as we speak.

The reason was a caching problem in meteor-babel. See https://github.com/meteor/meteor/issues/10262#issuecomment-428905810 .

1.1.2 === 1.1.4, but the upload of the build failed. Then I decided to keep the naming consistent with htm-compilers. However, that's not the reason why it was slow.
