### ISSUE TITLE
Code for version 1.1.2 and 1.1.4 is missing here

### ISSUE THREAD

**Issue by SimonSimCity** [Urigo/meteor-static-templates#22]
After discovering the issue #21 I saw that there are versions published on atmosphere which is not available here in this repository.

The last version available here is `1.1.1`, but atmosphere also has the versions `1.1.2` and `1.1.4` which are missing here, as of the time writing.

**Comment by sebakerckhof** [comment]
1.1.2 failed to upload. Which seems to happen sometimes when publishing multiple packages shortly after each other, probably a rate limit. But in that case you can't fix it except by pubishing a new version, hence 1.1.4. The code is now on here.
