### ISSUE TITLE
help with slow build

### ISSUE THREAD

**Issue by ghost** [Urigo/meteor-static-templates#23]
Hello, and thanks for all the work on this and other plugins.

I have been using this for a while, not realizing that it has been the cause of initial builds being slow. I ran METEOR_PROFILE=1 on building, and found that packages/urigo_static-html-compiler.js was taking a good 40 seconds.  I have about 150 html template files in my program.

I am using an old version of this package 0.1.8.  Would updating to the latest solve this problem?  I was looking at https://github.com/meteor/meteor/issues/10262 and it looks like some solutions were found.

I tried updating to the latest one, but I can't because meteor's complicated package selection system won't let me. In fact, I am still stuck on 1.6 because it's package managment system won't let me update to 1.8 because of some package.

Do you think updating would help - if I can figure out how, or are there any workarounds I could do with the old version?

Thanks in advance

**Comment by sebakerckhof** [comment]
Without the code I have to guess a little. Bit it's very likely that using the latest version on Meteor 1.8 would solve this

**Comment by ghost** [comment]
Ok.  I don't know what's up with my strange build thing. I just decided to bite the bullet and I'm going to convert the whole thing to vue.  Thx for the reply.
