### ISSUE TITLE
Importing  from same folder returns a empty object

### ISSUE THREAD

**Issue by shantanubhadoria** [Urigo/meteor-static-templates#3]
Hi Uri,
Thanks for your work on the angular meteor package. At the moment I am stuck on this very strange issue:

```
import template from './blogs.html';
console.log(template);

// blogs.html
<div> blah blah blah</div>
```

The console.log returns a empty Object{}. I have been scratching my head over it and I was wondering if you could guide me on it.

**Comment by shantanubhadoria** [comment]
Do note that when I import from a different folder, things seem to work fine. e.g.

```
import template from '../login/login.html';
console.log(template); // Shows the template contents correctly
```

**Comment by mishra-sumi** [comment]
I am also facing the same issue... @shantanubhadoria how did you solve that issue?
