### ISSUE TITLE
"Cannot find module" warnings

### ISSUE THREAD

**Issue by paralin** [Urigo/meteor-static-templates#5]
Not sure if this is a issue pre-meteor 1.4, but under Meteor 1.4 I get the following warnings: (for example)

```
imports/panel/panel-layout.ts (1, 22): Cannot find module './panel-layout.html'.
```

How can I eliminate these warnings? It does compile properly, but it puts about ~20-30 errors out while doing it.

**Comment by dotansimha** [comment]
TypeScript is a little tough with it's imports. 
Please try to import the template like this:

```
import template : string from './panel-layout.html';
```

You can find more solutions and ideas [here](https://github.com/Microsoft/TypeScript/issues/2709).

**Comment by paralin** [comment]
@dotansimha That does not work :( what you've just told me to do was a _suggested_ extension of the typescript language, not actually something implemented.

**Comment by dotansimha** [comment]
@paralin you are right, sorry. 
I can suggest you to try the "declare module" approach they suggested in that issue, it might work.

**Comment by kamilkisiela** [comment]
@paralin I've gathered couple of issues related to this inside #9. You can subscribe to it :)
