### ISSUE TITLE
Returns an Object {} instead of a template 

### ISSUE THREAD

**Issue by d4lek** [Urigo/meteor-static-templates#6]
Hello!

Right, so I have this issue when instead of a template it returns an object, and the cause is very strange, for example if I nest components too deeply, like folders inside of folders then template would become an object, if I nest it back by one folder then it would read it as it should... Does anybody has an explanation or a solution?

Thanks guys.

**Comment by nazarel** [comment]
@Urigo +1 Have the same issue. Custom Angular1 components only render properly when used within a ui-view.

Thanks for all the good work so far. Really loving using Angular-Meteor right now.

Currently used versions:
angular@1.5.7
angular-meteor@1.3.11
pbastowski:angular-babel@1.3.6
urigo:static-templates@0.1.0

**Comment by atd** [comment]
I have the same issue. The funny think is that it happens when the template starts with `l` in `../nav/songs/list.html`. It works ok if I change `list` with `rist` or other word, and bad with `lest`...

**Comment by dotansimha** [comment]
Hi @atd @nazarel @davidalekna ,
Please try to use version 0.1.1. 
Also, please make sure that your imports are like this:

```
import template from './a.html';
```

and do not use `require` to import the HTML templates.

**Comment by nazarel** [comment]
@dotansimha I am already importing using that syntax, as per the Angular-Meteor tutorials.

Currently I'm unable to update to version 0.1.1 as Meteor does not seem to be able to detect it.

The strange thing is that somewhere along the way it started to work. I continued development even though some elements don't render. I will continue to investigate the issue and see what changed to fix the issue.

**Comment by dotansimha** [comment]
And which Meteor version do you use? 
Also, are you using TypeScript or ES2016? 

And regarding 0.1.1 - it's my bad, we will release it in the new few minutes, and you will be able to test it.

**Comment by nazarel** [comment]
I am currently on Meteor 1.3.5.1
I am using ES2016, not TypeScript.

I started by following the Angular1-Meteor tutorial some time last year (at which point Angular2 was not available) and recently picked it back up for a new project. It's during a small refresher I did that I noticed not everything was working in the Angular1-Meteor tutorial, one component of which was the static-templates plugin.

**Comment by dotansimha** [comment]
@nazarel , please try to use 0.1.1 - it released just now. 
I tried to create a clean Meteor project with 1.3.5.1 and tried to add the 0.1.1 version of the package, I also used the original `ecmascript` package. 
Then, I tried to import html file using the syntax I mentioned in the previous comments and I got the actual string, and not an object. 

Please try it, and if you have any more issues, please share your `.meteor/packages` and `package.json` here.

Thanks.

**Comment by nazarel** [comment]
@dotansimha Will do. Thank you so much for the quick responses.

**Comment by dotansimha** [comment]
@nazarel 
I'm closing the issue at the moment - but feel free if you are still having issue with that.
