### ISSUE TITLE
TypeScript warnings about missing module

### ISSUE THREAD

**Issue by kamilkisiela** [Urigo/meteor-static-templates#9]
Every import statement of non JavaScript or TypeScript file throws a warning.

```
Cannot find module 'path/to/file`
```

For now, we can't handle those warnings. It could be done with special module declaration, but for each imported module, like this:

``` ts
declare module "path/to/file.html" {
    const template: string;
    export default template;
}
```

With `TypeScript@2.0` it will be possible to use wildcards inside module declarations.

``` ts
declare module "*.html" {
    const template: string;
    export default template;
}
```

Related: 
Urigo/meteor-static-templates#5
Urigo/angular2-meteor#275
Urigo/angular2-meteor#352
Microsoft/TypeScript#6615

**Comment by spookmx** [comment]
I tried declaring the module however I still get the error/warning and additional:
Invalid module name in augmentation, module './app.html' cannot be found.

I may be naming the module incorrectly...

**Comment by kamilkisiela** [comment]
@spookmx 

Let's say you have a file `client/imports/ui/list.html` and you want to remove a warning about missing module.

Create a file `client/imports/ui/list.html.d.ts` that contains:

``` ts
const template: string;
export default template;
```

There should be no warning now :)

**Comment by spookmx** [comment]
Hi @kamilkisiela, thanks for the quick follow up! It makes sense to have to specify the type of the importing module. However I'm still not clear how do we reference the `list.html.d.ts` file on the mail TS file.

I'm following the angular2 meteor tutorial and right on the first import is where I see the warning.

`import template from './app.html';`

**Comment by kamilkisiela** [comment]
@spookmx It depends on what is the contents of `app.html`. 

If it's a main template that contains `<head/>`, `<body/>` or both then you don't have to import it to the app. 

If it's a normal template that you're using to create a component then it suppose to work so you can open a new issue :) I'll investigate it.

**Comment by spookmx** [comment]
It is a normal template, I will do, thanks!

**Comment by yjose** [comment]
Good news  i put the simple code 
declare module "*.html" {
    const template: string;
    export default template;
}
in my typings/index.d.ts and it resolve my problem with declaration 
thank you @kamilkisiela

**Comment by kamilkisiela** [comment]
@yjose Glad to help!

**Comment by Urigo** [comment]
@kamilkisiela can we close this?
should we update something in the tutorials or it's already updated?

**Comment by kamilkisiela** [comment]
@Urigo it's included in the boilerplate we use, so yes, we can close this.

https://github.com/bsliran/angular2-meteor-base/blob/master/typings.d.ts
